# Generated by Django 5.0.6 on 2024-05-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('Clothe_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('contactNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.FloatField(default=0.0)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothe')),
                ('emailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.customer')),
            ],
        ),
    ]
