# Generated by Django 5.0.6 on 2024-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('adminEmailId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adminpassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('emailId', models.CharField(max_length=100)),
                ('ordernumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('totalbillamount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('amount_paid', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_st', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='age',
        ),
        migrations.AddField(
            model_name='clothe',
            name='category',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
