# Generated by Django 5.0.6 on 2024-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0002_adminmodel_orders_payment_remove_clothe_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothechild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('Clothe_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='ClotheWomen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('Clothe_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='gender',
        ),
    ]
