# Generated by Django 5.0.6 on 2024-05-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0003_clothechild_clothewomen_remove_clothe_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothewomen',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
