# Generated by Django 5.0.6 on 2024-05-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0004_clothewomen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothewomen'),
        ),
    ]
