# Generated by Django 5.0.6 on 2024-05-31 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0006_delete_clothechild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cid',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='clothe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothe'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='clothe_women',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothewomen'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
