# Generated by Django 5.0.6 on 2024-05-31 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0007_remove_cartmodel_cid_cartmodel_clothe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='Clothe_image',
            new_name='clothe_image',
        ),
        migrations.RenameField(
            model_name='clothewomen',
            old_name='Clothe_image',
            new_name='clothe_image',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='clothe',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='fashionapp.clothe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='clothe_women',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items_women', to='fashionapp.clothewomen'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='emailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='fashionapp.customer'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='totalPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clothewomen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
