# Generated by Django 5.0.6 on 2024-05-31 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0008_rename_clothe_image_clothe_clothe_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='clothe_image',
            new_name='Clothe_image',
        ),
        migrations.RenameField(
            model_name='clothewomen',
            old_name='clothe_image',
            new_name='Clothe_image',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='clothe_women',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothe'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='emailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.customer'),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clothewomen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
