# Generated by Django 5.0.6 on 2024-06-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0009_rename_clothe_image_clothe_clothe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothechild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=80)),
                ('Clothe_image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cwid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothewomen'),
            preserve_default=False,
        ),
    ]
