# Generated by Django 5.0.4 on 2024-06-21 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0010_clothechild_cartmodel_cwid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenAccessories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('Men_Accessoriesimage', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='WomenAccessories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('Women_Accessoriesimage', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='cwid',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothechild'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.womenaccessories'),
            preserve_default=False,
        ),
    ]
