# Generated by Django 5.0.6 on 2024-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0012_remove_cartmodel_aid_remove_cartmodel_cid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='cid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
