# Generated by Django 5.0.6 on 2024-06-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0013_cartmodel_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cid',
        ),
    ]
