# Generated by Django 5.0.4 on 2024-07-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0014_remove_cartmodel_cid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='clothe_child_cid',
            new_name='ccid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='clothe_cid',
            new_name='clothe_id',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='clothe_women_cid',
            new_name='cwid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='men_aid',
            new_name='maid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='women_aid',
            new_name='waid',
        ),
        migrations.RenameField(
            model_name='clothechild',
            old_name='id',
            new_name='ccid',
        ),
        migrations.RenameField(
            model_name='clothewomen',
            old_name='id',
            new_name='cwid',
        ),
        migrations.RenameField(
            model_name='menaccessories',
            old_name='id',
            new_name='maid',
        ),
        migrations.RenameField(
            model_name='womenaccessories',
            old_name='id',
            new_name='waid',
        ),
    ]
