# Generated by Django 5.0.4 on 2024-07-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0015_rename_clothe_child_cid_cartmodel_ccid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='clothe_id',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='clothe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothe'),
        ),
    ]
