# Generated by Django 5.0.4 on 2024-07-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0017_rename_waid_cartmodel_aid_rename_ccid_cartmodel_cid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='cid',
            new_name='clothe_child',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='emailId',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='aid',
            new_name='women_accessory',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='clothe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothe'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='clothe_women',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothewomen'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='men_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.menaccessories'),
        ),
    ]
