# Generated by Django 5.0.4 on 2024-07-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0018_rename_cid_cartmodel_clothe_child_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='women_accessory',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='clothe_child',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='customer',
            new_name='emailId',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='clothe',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='clothe_women',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='men_accessory',
        ),
    ]
