# Generated by Django 5.0.4 on 2024-07-17 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0019_rename_women_accessory_cartmodel_aid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='aid',
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fashionapp.clothe'),
        ),
    ]
